sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: aegir-debian-9

script:
  - bundle exec kitchen verify ${INSTANCE}

